# Generated by Django 5.2.2 on 2025-06-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('productId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(max_length=50)),
                ('deliveryOptionId', models.CharField(max_length=50)),
            ],
        ),
    ]
