# Generated by Django 5.2.2 on 2025-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('stars', models.IntegerField(max_length=50)),
                ('count', models.IntegerField(max_length=50)),
                ('priceCents', models.IntegerField(max_length=50)),
            ],
        ),
    ]
