# Generated by Django 5.2.2 on 2025-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0002_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='priceCents',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='stars',
            field=models.IntegerField(),
        ),
    ]
