# Generated by Django 5.2.2 on 2025-06-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0003_alter_cart_quantity_alter_products_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stars',
            field=models.FloatField(),
        ),
    ]
