# Generated by Django 5.2.2 on 2026-04-01 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon_app', '0006_rename_order_id_order_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='deliveryOptionId',
            new_name='delivery_option_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='productId',
            new_name='product_id',
        ),
    ]
